### ISSUE TITLE
zim index files

### ISSUE THREAD

**Issue by fabionar** [jjzz/ZZ-WordFreq#1]
I'm sorry to ask here, but I can't find any contact info on you.

http://104.236.5.216/work/wiki.index/ 
This server stopped working, and I used your wiki.index file since it's great. Can you share a link with the english one, or maybe even create an updated version?

**Comment by jjzz** [comment]
This is for the 2017.07 wiki en novid version only, (note: NOT the lastest version)

    http://45.63.86.128:10080/wikipedia_en_all_novid_2017-07.zim.index

Download zim from,

    http://download.kiwix.org/zim/wikipedia/

If you're using other version, and your RAM is less than 8GB, better go ask your friend to index it for you. Indexing will be done in 20 minutes.

**Comment by andradadad** [comment]
Hello, could you still provide this for an updated version?
I don't see this anywhere. No friends, though :/

**Comment by jjzz** [comment]
i would suggest to get some extra RAM for your computer if  that's the case. old RAMs are very easy to find in the second-hand market or online market, and it's pretty cheap now.

or, you can use Kiwix's software or mobile app directly, from kiwix.org.

anyway, if you still want to use wiki zim on goldendict and cannot get it done, tell me which wiki file you are using. i'll try.

**Comment by andradadad** [comment]
> i would suggest to get some extra RAM for your computer if that's the case. old RAMs are very easy to find in the second-hand market or online market, and it's pretty cheap now.
> 
> or, you can use Kiwix's software or mobile app directly, from kiwix.org.
> 
> anyway, if you still want to use wiki zim on goldendict and cannot get it done, tell me which wiki file you are using. i'll try.

Thank you for replying!

I would like the Wikipedia English, since it's so heavy my computer can't even index the headwords! And it usually takes hours to finish just to see it crash, returning to zero point. So, basically not even the normal articles I have access instead of full-search.

Basically one of these then:

https://download.kiwix.org/zim/wikipedia/wikipedia_en_all_maxi_2024-01.zim
https://download.kiwix.org/zim/wikipedia/wikipedia_en_all_nopic_2024-02.zim

If there's time left, and you would like even to post here on github, you could do the full-search availability for other languages too. There's nowhere else for .index files on the internet.
I picked nopic randomly just to be the smallest files, tried the most recent but there's one on 2023. The english above is more necessary for the huge size.
Less necessary:

https://download.kiwix.org/zim/wikipedia/wikipedia_de_all_nopic_2024-03.zim
https://download.kiwix.org/zim/wikipedia/wikipedia_es_all_nopic_2024-02.zim
https://download.kiwix.org/zim/wikipedia/wikipedia_fr_all_nopic_2024-03.zim
https://download.kiwix.org/zim/wikipedia/wikipedia_gl_all_maxi_2024-03.zim
https://download.kiwix.org/zim/wikipedia/wikipedia_it_all_nopic_2024-02.zim
https://download.kiwix.org/zim/wikipedia/wikipedia_la_all_nopic_2024-02.zim
https://download.kiwix.org/zim/wikipedia/wikipedia_pt_all_nopic_2023-12.zim
https://download.kiwix.org/zim/wikipedia/wikipedia_ru_all_nopic_2024-02.zim

**Comment by jjzz** [comment]
```
https://anonymfile.com/n08RW/wikipedia-enallmaxi2024-01zim.index
```
download the `wikipedia_en_all_maxi_2024-01.zim.index` and copy to the 0-Byte hash file generated in `~/.goldendict/index`. hope it works.
I switched off FTS/full text search on huge zim file. eg. only allowing FTS on dicts containing less than 1,000,000 articles.

as for language, I have wikipedia-en only. Sorry for that.
strong ambition needs strong hardware.

**Comment by andradadad** [comment]
> ```
> https://anonymfile.com/n08RW/wikipedia-enallmaxi2024-01zim.index
> ```
> 
> download the `wikipedia_en_all_maxi_2024-01.zim.index` and copy to the 0-Byte hash file generated in `~/.goldendict/index`. hope it works. I switched off FTS/full text search on huge zim file. eg. only allowing FTS on dicts containing less than 1,000,000 articles.
> 
> as for language, I have wikipedia-en only. Sorry for that. strong ambition needs strong hardware.

`'Sorry, File does not exist on this server. '`

Couldn't upload here on github or anywhere else that doesn't delete?

**Comment by jjzz** [comment]
[REDACTED]

**Comment by andradadad** [comment]
It shows on the dictionaries successfully.
But it's not showing the articles through common searches on the default goldendict entries mainpage.

Any idea how to make it work?

**Comment by jjzz** [comment]
> Any idea how to make it work?

Never know what you called "default goldendict entries mainpage".

I only use the edit control in navigation bar (menu: `view` - `Navigation`) to search entries.

**Comment by andradadad** [comment]
> I only use the edit control in navigation bar (menu: `view` - `Navigation`) to search entries.
Exactly what I mean. If I start typing in the search, in a group that I created exclusively for the file, it shows the exact titles as suggestions in autofill as I type. 

But, when entering the title of the article it shows there's nothing found.

That is, it does not work as a dictionary like any other .zim or .bgl, etc.
Even that it shows successfully in the list of dictionaries and it prompts pretyped suggestions to articles of wikipedia, it doesn't actually show the main article in goldendict.
By simply cancelling an index and renaming the files it seems like something isn't quite working as the other wikipedia working files.

**Comment by jjzz** [comment]
Sorry to hear that.
Maybe a simple memory stick will make life easier.
Good luck!
